import Link from 'next/link';
import {Icon} from '@/components/icons';

const capabilities=[
  ['01','Observe','Analyse les emails, rendez-vous, documents et signaux commerciaux connectés.'],
  ['02','Décide','Classe les priorités selon leur valeur, leur urgence et tes règles.'],
  ['03','Prépare','Rédige les réponses, relances, comptes rendus et prochaines actions.'],
  ['04','Exécute','Lance les actions autorisées et te demande de valider les décisions sensibles.'],
];

export default function OfferPage(){return <main className="min-h-screen overflow-hidden bg-[#05070b] px-5 text-white">
  <nav className="mx-auto flex h-20 max-w-7xl items-center justify-between border-b border-white/10"><Link href="/" className="flex items-center gap-3"><span className="forge-mark">F</span><span><strong className="block tracking-[.1em]">FORGE AI</strong><small className="font-mono text-[8px] uppercase tracking-[.2em] text-slate-500">Autonomous operating system</small></span></Link><div className="flex items-center gap-2"><a href="https://atl-portfolio.pages.dev/#products" className="btn-ghost hidden sm:inline-flex">Catalogue produits</a><Link href="/auth" className="btn-muted">Ouvrir le cockpit</Link></div></nav>
  <section className="relative mx-auto grid min-h-[72vh] max-w-7xl items-center gap-12 py-20 lg:grid-cols-[1.1fr_.9fr]"><div className="pointer-events-none absolute left-1/3 top-1/4 h-72 w-72 rounded-full bg-violet-600/20 blur-[120px]"/><div className="relative"><p className="eyebrow mb-6">AGENT OPÉRATIONNEL · SOUS TON CONTRÔLE</p><h1 className="max-w-4xl text-5xl font-black leading-[.94] tracking-[-.045em] sm:text-7xl lg:text-8xl">Ton agent exécute.<br/><span className="text-lime-300">Tu gardes le contrôle.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-400">Forge AI transforme tes emails, ton agenda et tes documents en actions concrètes : priorités, relances, rendez-vous et suivi commercial.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/auth" className="btn-primary">Configurer mon agent <Icon name="arrow"/></Link><Link href="/autopilot" className="btn-muted">Voir l’autopilote</Link></div><p className="mt-5 font-mono text-[10px] uppercase tracking-widest text-slate-600">Gmail · Google Calendar · Google Drive · Validation humaine</p></div>
  <div className="relative rounded-3xl border border-white/10 bg-white/[.035] p-4 shadow-2xl shadow-violet-950/40 backdrop-blur-xl"><div className="flex items-center justify-between border-b border-white/10 px-3 pb-4"><div><p className="font-mono text-[9px] uppercase tracking-[.2em] text-slate-500">État du système</p><strong className="mt-1 block text-lg">Agent en ligne</strong></div><span className="h-3 w-3 rounded-full bg-lime-300 shadow-[0_0_18px_#bef264]"/></div><div className="space-y-2 pt-4">{['Relancer les 3 prospects chauds','Préparer le rendez-vous de 14:00','Classer 7 emails importants'].map((item,i)=><div key={item} className="flex items-center gap-4 rounded-xl border border-white/[.07] bg-black/20 p-4"><span className="grid h-9 w-9 place-items-center rounded-lg bg-lime-300/10 font-mono text-xs text-lime-300">0{i+1}</span><div className="min-w-0 flex-1"><strong className="block truncate text-sm">{item}</strong><span className="text-xs text-slate-500">Prêt à valider</span></div><span className="text-lime-300">→</span></div>)}</div></div></section>
  <section className="mx-auto max-w-7xl border-t border-white/10 py-20"><div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">UNE BOUCLE COMPLÈTE</p><h2 className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">De l’information à l’action.</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">L’autonomie augmente progressivement. Les actions sensibles restent soumises à ton approbation.</p></div><div className="grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 md:grid-cols-4">{capabilities.map(([no,title,body])=><div key={no} className="bg-[#080b11] p-6"><span className="font-mono text-xs text-lime-300">{no}</span><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{body}</p></div>)}</div></section>
  <section className="mx-auto mb-20 grid max-w-7xl gap-8 rounded-3xl border border-violet-400/20 bg-gradient-to-br from-violet-500/10 to-lime-300/5 p-8 sm:p-12 md:grid-cols-[1fr_auto] md:items-center"><div><p className="eyebrow">PRÊT À TRAVAILLER</p><h2 className="mt-3 text-3xl font-bold sm:text-5xl">Connecte tes outils une fois.<br/>Forge s’occupe du reste.</h2></div><div className="flex flex-col gap-3"><Link href="/auth" className="btn-primary">Entrer dans Forge AI <Icon name="arrow"/></Link><a href="https://atl-portfolio.pages.dev/#products" className="btn-muted justify-center">Voir les produits indépendants</a></div></section>
</main>}
