'use client';
import {useState} from 'react';import {Icon} from './icons';
const products=[
 {key:'forgem',index:'01',label:'IDENTITÉ',name:'Forgem',tagline:'Une marque entière. Pas un logo de plus.',copy:'Forgem transforme quelques intentions en un système visuel cohérent, exportable et immédiatement utilisable.',price:'29 €',cadence:'une fois',cta:'Créer ma marque',checkout:'https://buy.stripe.com/dRmfZgfHf1s2gruap55c402',demo:'https://brand-kit-studio.pages.dev',metrics:[['14','modules créatifs'],['1 clic','export complet'],['0','abonnement']],features:['Palette et contraste automatiques','Assets web et fichiers dev-ready','Kit complet exporté en ZIP'],tone:'lime'},
 {key:'ugc-engine',index:'02',label:'CONTENU',name:'UGC Engine',tagline:'La photo reste vraie. La campagne prend vie.',copy:'UGC Engine transforme une vraie photo produit en créations vidéo premium, déclinées pour chaque surface sociale.',price:'59 €',cadence:'par mois',cta:'Ouvrir mon studio',checkout:'https://buy.stripe.com/bJe00i66F0nY1wAgNt5c401',demo:'https://ugc-engine.allan-tchicaya.workers.dev',metrics:[['3','formats sociaux'],['24','variantes / campagne'],['0 €','IA générative']],features:['Rendus 9:16, 4:5 et 1:1','Variantes de hooks et durées','Fidélité totale au produit'],tone:'violet'},
 {key:'kern-inbox',index:'03',label:'OPÉRATIONS',name:'KERN Inbox',tagline:'Le chaos des emails devient une opération nette.',copy:'KERN structure chaque demande, retrouve la procédure, prépare la réponse et attend la décision humaine.',price:'Sur mesure',cadence:'dès 249 €/mois',cta:'Planifier l’installation',checkout:'/onboarding?product=kern-inbox',demo:'https://kern-inbox.allan-tchicaya.workers.dev',metrics:[['7','écrans métier'],['100 %','actions traçables'],['0','envoi sans accord']],features:['Routage et risque déterministes','Checklists issues des procédures','Journal d’audit append-only'],tone:'cyan'}
] as const;
function ProductVisual({kind}:{kind:string}){if(kind==='forgem')return <div className="catalog-visual forgem-visual"><div className="brand-sheet"><span>FORGEM / SYSTEM 01</span><strong>MONOLITH</strong><p>precision · velocity · form</p><div className="brand-palette"><i/><i/><i/><i/></div><div className="brand-type">Aa <small>Archivo Black<br/>DM Sans</small></div></div><div className="asset-card asset-a">M</div><div className="asset-card asset-b">MONO<br/><b>02</b></div></div>;
if(kind==='ugc-engine')return <div className="catalog-visual ugc-visual"><div className="phone-frame"><div className="ugc-product"><span>NEW DROP</span><div className="ugc-object">UGC</div><strong>MAKE THEM<br/>STOP.</strong><button>SHOP NOW</button></div></div><div className="format-chip chip-a">9:16</div><div className="format-chip chip-b">4:5</div><div className="render-line"><i/><span>RENDERING 86%</span></div></div>;
return <div className="catalog-visual kern-visual"><div className="mail-stack"><div className="mail-row"><i className="urgent"/><span><b>Redemption request</b><small>Risk review required</small></span><em>HIGH</em></div><div className="mail-row"><i/><span><b>Investor onboarding</b><small>Procedure matched · 8 steps</small></span><em>READY</em></div><div className="mail-row"><i/><span><b>NAV approval</b><small>Draft response prepared</small></span><em>REVIEW</em></div></div><div className="audit-radar"><span>POLICY</span><strong>PASS</strong><small>human approval required</small></div></div>}
export function ProductCatalogue(){const [active,setActive]=useState(1);const p=products[active];return <>
 <div className="catalog-tabs" role="tablist">{products.map((item,i)=><button key={item.key} onClick={()=>setActive(i)} className={i===active?'active':''} role="tab" aria-selected={i===active}><span>{item.index}</span><b>{item.name}</b><small>{item.label}</small></button>)}</div>
 <article className={`catalog-stage catalog-${p.tone}`}><div className="catalog-copy"><p className="eyebrow">{p.label} / {p.index}</p><h2>{p.tagline}</h2><p className="catalog-description">{p.copy}</p><div className="catalog-metrics">{p.metrics.map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><ul>{p.features.map(x=><li key={x}><Icon name="check" size={14}/>{x}</li>)}</ul><p className="catalog-price"><strong>{p.price}</strong><span>{p.cadence}</span></p><div className="catalog-actions"><a href={p.checkout} className="btn-primary">{p.cta}<Icon name="arrow"/></a><a href={p.demo} target="_blank" rel="noreferrer" className="catalog-demo">Explorer la démo <span>↗</span></a></div></div><ProductVisual kind={p.key}/></article>
 </>}
